/**
 * Created by Administrator on 2017/3/29.
 */
// 总网页导航
export const INDEXNAV = 'INDEXNAV'
// 首页
export const INDEX = 'INDEX'
// 登录
export const LOGIN = 'LOGIN'
// 注销
export const LOGOUT = 'LOGOUT'
// 系统操作员管理
export const SYSTEM_MANAGER__OPERATOR = 'SYSTEM_MANAGER__OPERATOR'
// 新增系统操作员
export const SYSTEM_MANAGER__ADDOPERATOR = 'SYSTEM_MANAGER__ADDOPERATOR'
// 角色管理
export const SYSTEM_MANAGER__ROLE = 'SYSTEM_MANAGER__ROLE'
// 角色权限管理
export const SYSTEM_MANAGER__ROLEPROMISSON = 'SYSTEM_MANAGER__ROLEPROMISSON'
// 消息管理
export const SYSTEM_MANAGER__MESSAGE = 'SYSTEM_MANAGER__MESSAGE'
// 渠道管理首页
export const CHANNEL_MANAGEMENT__INDEX = 'CHANNEL_MANAGEMENT__INDEX'
// 客户管理首页
export const CUSTOMER_MANAGER__INDEX = 'CUSTOMER_MANAGER__INDEX'
// 产品管理首页
export const PRODUCT_MANAGEMENT__INDEX = 'PRODUCT_MANAGEMENT__INDEX'
// 审贷管理首页
export const LOAN_APPROVAL_MANAGEMENT__INDEX = 'LOAN_APPROVAL_MANAGEMENT__INDEX'
// 尽调管理首页
export const DUE_DILIGENCE_MANAGEMENT__INDEX = 'DUE_DILIGENCE_MANAGEMENT__INDEX'
// 财务管理首页
export const FINANCIAL_MANAGEMENT__INDEX = 'FINANCIAL_MANAGEMENT__INDEX'
// 贷后管理首页
export const POST_LOAN_MANAGEMENT__INDEX = 'POST_LOAN_MANAGEMENT__INDEX'
// 报表管理首页
export const REPORT_MANAGEMENT__INDEX = 'REPORT_MANAGEMENT__INDEX'

